spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redostore
    username: postgres
    password: enolagay
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: barang-service

server:
  port: 8080
